### ISSUE TITLE
Build the "personal" group type

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-Groups#40]
For Omeka Commons, we've talked about a group -- automatically created when a new user registers -- that is only accessible by the owner. Some yet-to-be-decided special handling and display will be called for to hide irrelevant group features (e.g., invitations) and to distinguish it from regular groups.

This puts a point on the idea that "groups" are groups of items, not groups of users.

NB -- this group type is essentially what "MyOmeka" did, so this might be the replacement for it, partially depending on thoughts about the dependence on RecordRelations.

@sheilabrennan , @sharonmleon : is this your understanding of the direction we're going as well?

**Comment by sheilabrennan** [comment]
Yes, that seems right to me.
