### ISSUE TITLE
Interaction with Commenting problems

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-Groups#5]
The complex joins to limit access to comments by group is dandy, but if a comment is not associated with any group it is absent from the results.

Either need to figure a way to make the query branch based on whether the join to RecordRelationsRelation has any result -- no idea if that's even possible in SQL -- or create a workaround hidden Group to put all the Comments with no Group association into.

I think that the visibility filter on GroupTable could filter that out of the usual queries while keeping the Group in existence for associating Comments.

**Comment by zerocrates** [comment]
outer join (with maybe some checks against NULL results if that's important to this situation)?
